# Generated by Django 4.2.7 on 2023-11-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                ("goalID", models.AutoField(primary_key=True, serialize=False)),
                ("goalName", models.CharField(max_length=30)),
                ("goalAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currentAmount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("description", models.TextField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savingGoals",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
