# Generated by Django 4.2.7 on 2023-11-22 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lender",
            fields=[
                ("lenderID", models.AutoField(primary_key=True, serialize=False)),
                ("lenderName", models.CharField(max_length=255)),
                ("contactEmail", models.EmailField(max_length=254)),
                ("contactPhone", models.CharField(max_length=20)),
                ("address", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LoanAccount",
            fields=[
                ("loanID", models.AutoField(primary_key=True, serialize=False)),
                ("loanAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("interestRate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("loanTerm", models.PositiveIntegerField()),
                ("paymentFrequency", models.CharField(max_length=20)),
                ("paymentStartDate", models.DateField()),
                ("monthlyPaymentDue", models.DateField()),
                (
                    "lender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lenders",
                        to="creditManagement.lender",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loanAccounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditCardAccount",
            fields=[
                ("creditCardID", models.AutoField(primary_key=True, serialize=False)),
                ("cardNumber", models.CharField(max_length=16)),
                ("cardHolderName", models.CharField(max_length=255)),
                (
                    "cardType",
                    models.CharField(
                        choices=[
                            ("Visa", "Visa"),
                            ("MasterCard", "Mc"),
                            ("American express", "Amex"),
                            ("Other", "Other"),
                        ],
                        default="Visa",
                        max_length=20,
                    ),
                ),
                ("creditLimit", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "availableCredit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("paymentDueDate", models.DateField()),
                ("billing_cycle_start", models.DateField()),
                ("billing_cycle_end", models.DateField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creditCardAccounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
