# Generated by Django 4.2.7 on 2023-11-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creditManagement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanaccount",
            name="monthlyPaymentDue",
        ),
        migrations.AlterField(
            model_name="loanaccount",
            name="paymentFrequency",
            field=models.CharField(
                choices=[
                    ("Weekly", "Weekly"),
                    ("By-weekly", "Byweekly"),
                    ("Monthly", "Monthly"),
                    ("Quartrly", "Quarterly"),
                ],
                default="Monthly",
                max_length=20,
            ),
        ),
    ]
