# Generated by Django 4.2.7 on 2023-11-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("creditManagement", "0002_remove_loanaccount_monthlypaymentdue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanaccount",
            name="lender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lenders_accounts",
                to="creditManagement.lender",
            ),
        ),
    ]
