# Generated by Django 4.2.7 on 2023-11-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("accountID", models.AutoField(primary_key=True, serialize=False)),
                ("accountNumber", models.IntegerField()),
                (
                    "accountType",
                    models.CharField(
                        choices=[("Chequing", "Chequing"), ("Saving", "Saving")],
                        default="Chequing",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
